#!/usr/bin/env python

import sys

from arm_control_plugin.arm_control import MyPlugin
from rqt_gui.main import Main

plugin = 'arm_control_plugin'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))