#!/usr/bin/env python

import sys

from current_sensor_plugin.plugin import CurrentSensorPlugin
from rqt_gui.main import Main

plugin = 'current_sensor_plugin'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))