#!/usr/bin/env python

import sys

from ld_linearactuator_plugin.linearactuator import MyPlugin
from rqt_gui.main import Main

plugin = 'ld_linearactuator_plugin'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))