#!/usr/bin/env python

import sys

from life_detection_plugin.plugin import LifeDetectionPlugin
from rqt_gui.main import Main

plugin = 'life_detection_plugin'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))